---
# tasks file for metallb

# Copyright (C) 2020 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: initialize images fact
  set_fact:
    images:
      - { repository: 'metallb/speaker', tag: "{{ metallb_version }}" }
      - { repository: 'metallb/controller', tag: "{{ metallb_version }}" }
  when:
    images_cache_path is defined
  tags:
    - metallb

- name: load {{ images }} from cache
  include_tasks: retrieve_container_image.yml
  loop: "{{ images }}"
  when:
    images_cache_path is defined
  tags:
    - metallb

- name: ensure metallb is running
  block:
  - name: ensure /home/{{ ansible_user_id }}/metallb exists
    file:
      path: /home/{{ ansible_user_id }}/metallb
      state: directory

  - name: ensure metallb.yml is in place at /home/{{ ansible_user_id }}/metallb
    template:
      src: templates/metallb.yml.j2
      dest: /home/{{ ansible_user_id }}/metallb/metallb.yml
      force: yes
      mode: u=rw,g=r

  - name: ensure metallb-configmap.yml is in place at /home/{{ ansible_user_id }}/metallb
    copy:
      src: files/metallb-configmap.yml
      dest: /home/{{ ansible_user_id }}/metallb/metallb-configmap.yml
      force: yes
      mode: u=rw,g=r

  - name: ensure metallb is running
    shell: |
      kubectl --kubeconfig=/home/{{ ansible_user_id }}/kubeconfig.yml apply -f /home/{{ ansible_user_id }}/metallb//metallb.yml
      kubectl --kubeconfig=/home/{{ ansible_user_id }}/kubeconfig.yml apply -f /home/{{ ansible_user_id }}/metallb/metallb-configmap.yml
  tags:
    - metallb

- name: save {{ images }} to cache
  include_tasks: cache_container_image.yml
  loop: "{{ images }}"
  when:
    images_cache_path is defined  
  tags:
    - metallb
